# These are supported funding model platforms

github: [cyyjs]
patreon: cyyjs
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # cyyjs
otechie: # Replace with a single Otechie username
custom: ['https://paypal.me/cyy888']
